---

##
# System wide set.
##

# Install deps
- name: "apt-get update && dist-upgrade"
  apt:
    update_cache: yes
    # One day
    cache_valid_time: 86400 

- name: "Required packages"
  apt:
    name: "{{ item }}"
    state: present
  tags: base
  with_items: "{{ packages }}"

- name: "Unpack shell files"
  unarchive:
    src: oh-my-zsh.tar.xz
    dest: /etc
    creates: /etc/oh-my-zsh
    owner: root
    group: root
    
- name: "Shell files for skel"
  copy:
    src: "shell/{{ item }}"
    dest: "/etc/skel/.{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items: "{{ shell_files }}"

- name: "Gather home locations"
  shell: "getent passwd {{ item }} | cut -d: -f6"
  check_mode: no
  changed_when: no
  with_items: "{{ set_shell }}"
  register: "user_homes"

- name: "Shell files for managed users"
  copy:
    src: "shell/{{ item[1] }}"
    dest: "{{ item[0]['stdout'] }}/.{{ item[1] }}"
  when: item.0.stdout != ''
  with_nested:
    - "{{ user_homes.results }}"
    - "{{ shell_files }}"

- name: "Script for users left behind"
  template:
    src: where-is-my-shell.sh
    dest: /usr/local/bin/where-is-my-shell.sh
    owner: root
    group: root
    mode: "0755"

- name: "Change shell to zsh"
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items: "{{ set_shell }}"
