set nocp
syntax on

set pastetoggle=<F5>

map <M-g> <ESC>:tabnew<CR>
map <M-y> <ESC>:tabnext<CR>
map <M-r> <ESC>:tabprevious<CR>

map <M-z> <ESC>:next<CR>
map <M-x> <ESC>:prev<CR>
map <F4> <ESC>:make<CR>

set wildmenu

map <C-t> <ESC>:TlistToggle<CR>
map <C-f> <ESC>:set invnumber<CR>

au BufNewFile,BufRead *.latex setlocal spell spelllang=pl
au BufNewFile,BufRead *.latex set textwidth=75
au BufNewFile,BufRead *.template set filetype=html 
au BufNewFile,BufRead *.mako set filetype=html 
au BufNewFile,BufRead *.m set filetype=objc
au BufNewFile,BufRead *.pp set filetype=puppet
au BufNewFile,BufRead *.ml set tabstop=2 expandtab shiftwidth=2
au BufNewFile,BufRead *.py set tabstop=4 expandtab smarttab smartindent shiftwidth=4
au BufNewFile,BufRead *.rb set tabstop=4 expandtab smarttab smartindent shiftwidth=4

autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType inc set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete

set foldmethod=marker

