# Installed with Ansible

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=/etc/oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="gentoo"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git debian dirhistory python sudo)

source $ZSH/oh-my-zsh.sh


# User configuration
alias hogs='du -s * | sort -n'
alias go='sudo -i -u'


setopt nohup
setopt no_bg_nice
setopt no_clobber       # For > --> >|   &| means disowned
setopt nobeep
setopt multios          # echo foo > file1 | command instead of tee
setopt rcquotes		# Elegant inclusion of quotes in quotes.
# watch="notme"
# logcheck=60

# Jumping/removing words
WORDCHARS='*?_-[]~=!#$%^(){}<>'

RPROMPT='%{$fg_bold[grey]%}(%D{%H:%M%P} : %D{%d/%m/%y})%{$reset_color%}'

EDITOR="vim"

# History basic
setopt HIST_IGNORE_SPACE
HISTFILE=~/.history
HISTSIZE=20000
SAVEHIST=20000


if [ -f "$HOME/.zshrc_private" ]; then
	source ~/.zshrc_private
fi
